name: Vercel Preview Deployment
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN}}
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
                node-version: '18.18.0'
          - name: Install node modules
            run: yarn
            run: echo "hello world"
          - name: Build the project
            run: yarn run build
          - name: Sets the vercel env
            run: |
              cd build
              mkdir .vercel
              touch project.json
              echo '{\"orgId\":\"$VERCEL_ORG_ID\",\"projectId\":\"$VERCEL_PROJECT_ID\"}' > project.json
          - name: Deploying the project
            run: yarn deploy --token=${{ secrets.VERCEL_TOKEN }}
          - name: Setup finish
            run: echo "hurray!"